version: 1.3.{build}

branches:
  only:
    - master
    - dev
    - debug

skip_tags: true

image: Visual Studio 2017

# Install pester module and init the Appveyor support.
install:
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force -Verbose
  - ps: Import-PackageProvider NuGet -MinimumVersion '2.8.5.201' -Force
  - ps: Install-Module -Name 'Pester' -Scope CurrentUser -Force -SkipPublisherCheck -AllowClobber
  - ps: Update-Module 'Pester'
  - ps: Install-Module -Name 'PSCoverage' -Scope CurrentUser -Force -SkipPublisherCheck -AllowClobber
  - ps: Import-Module 'PSCoverage' -Force
  - ps: Import-Module .\tools\AppVeyor.psm1

environment:
  NuGetToken:
    secure: 835qfZIkC9mE7QhkYfOZVAdR8rZhPvxG8BO4CbeaelRQOhlqmaSr8G1DWRJzZ/bS
  CoverallsToken:
    secure: nyiBjGDC07q/4OmKINxOfkwGPCywtNeGMmTzoSicmHMqOWycW8DZoJRagRTDEucc

build: false

before_build:
  - ps: Invoke-AppVeyorBumpVersion

build_script:
  - ps: Invoke-AppVeyorBuild

test_script:
  - ps: Invoke-AppVeyorTests
  - ps: Invoke-CoverageReport

deploy:
  - provider: GitHub
    auth_token:
      secure: M+bBX5/nKdJB0eViP7xtrLVTwf3vGDUA9N2MMprZp2i+9ZR3CBVcJnSzJWUmalhB
    artifact: Ponduit.zip           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only

after_deploy:
  - ps: Invoke-AppVeyorPSGallery
