version: 1.3.{build}

image: Visual Studio 2015

# Install pester module and init the Appveyor support.
install:
  - cinst pester
  - ps: Import-Module .\tools\AppVeyor.psm1

environment:
  NuGetToken:
    secure: 835qfZIkC9mE7QhkYfOZVAdR8rZhPvxG8BO4CbeaelRQOhlqmaSr8G1DWRJzZ/bS

build: false

build_script:
  - ps: Invoke-AppVeyorBuild

test_script:
  - ps: Invoke-AppVeyorTests

deploy:
  - provider: GitHub
    auth_token:
      secure: M+bBX5/nKdJB0eViP7xtrLVTwf3vGDUA9N2MMprZp2i+9ZR3CBVcJnSzJWUmalhB
    artifact: Ponduit.zip           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
