#
# Module manifest for module 'Ponduit'
#
# Generated by: OCram85
#
# Generated on: 08.12.2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Ponduit.psm1'

# Version number of this module.
# We need to replace this var manually. Otherwise this manifest could not be read by poweshell.
ModuleVersion = $Env:APPVEYOR_BUILD_VERSION

# ID used to uniquely identify this module
GUID = '83913031-bbde-4b82-b00d-7d45faafe62f'

# Author of this module
Author = 'OCram85'

# Company or vendor of this module
CompanyName = 'OCram85'

# Copyright statement for this module
Copyright = 'OCram85'

# Description of the functionality provided by this module
Description = 'Ponduit provides a simple CLI interface for Phabricator through Conduit API calls.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @('Classes\ClassLoader.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @(
    '.\Format\PonduitConduitConfig.Format.ps1xml'
)

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @(
    'Get-ConduitConfig',
    'Set-ConduitConfig',
    'Update-ConduitMethods',
    'Invoke-ConduitMethod'
)

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('powershell', 'phabricator', 'Ponduit', 'conduit')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/OCram85/Ponduit/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/OCram85/Ponduit'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/OCram85/Ponduit'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

